class CommandEnum:
    HANDSHAKE = 'handshake'
    HANDSHAKE_RESPONSE = 'handshake_response'
    PING = 'ping'
    PONG = 'pong'
    ERROR = 'error'
    REGISTER_SERVICE = 'register_service'
    REGISTER_SERVICE_RESPONSE = 'register_service_response'
    SERVICE_REQUEST = 'service_request'
    CONNECTION_ESTABLISHED = 'connection_established'
    CLOSE_CONNECTION = 'close_connection'
    CONNECTION_CLOSED = 'connection_closed'
    SEND_MESSAGE = 'send_message'
    MESSAGE_RECEIVED = 'message_received'
